---
- name: Ensure .ssh directory exists
  ansible.builtin.file:
    path: "{{ ssh_config_file | dirname | expanduser }}"
    state: directory
    mode: "0700"
    owner: "{{ ssh_config_owner }}"
    group: "{{ ssh_config_group }}"

- name: Generate SSH config file
  ansible.builtin.template:
    src: ssh_config.j2
    dest: "{{ ssh_config_file | expanduser }}"
    mode: "{{ ssh_config_mode }}"
    owner: "{{ ssh_config_owner }}"
    group: "{{ ssh_config_group }}"
